# Generated by Django 2.0 on 2021-08-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='t_c',
            field=models.BooleanField(default=False),
        ),
    ]
