# Generated by Django 2.0 on 2021-09-13 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210913_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pimg1', models.ImageField(upload_to='product_images/')),
                ('pimg2', models.ImageField(upload_to='product_images/')),
                ('pimg3', models.ImageField(upload_to='product_images/')),
                ('pname', models.CharField(max_length=200)),
                ('pdes', models.TextField()),
                ('Seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Seller')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Categories')),
            ],
        ),
    ]
